# Generated by Django 2.2 on 2023-02-07 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=2000)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=2000)),
                ('price', models.CharField(blank=True, default='0', max_length=200)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='0', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('type_event', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Post')),
            ],
        ),
    ]
