# Generated by Django 2.2 on 2023-11-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20231025_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='email',
            new_name='live',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='air',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='home',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='job',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type_event',
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='Ticbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=200)),
                ('ticket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, default='0', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default='0', max_length=200)),
                ('job', models.CharField(default='0', max_length=200)),
                ('sex', models.CharField(default='0', max_length=200)),
                ('home', models.CharField(default='0', max_length=200)),
                ('air', models.CharField(default='0', max_length=200)),
                ('phone', models.CharField(default='0', max_length=200)),
                ('type_event', models.CharField(default='0', max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Post')),
            ],
        ),
    ]
